MESSAGE_END = ";"
MESSAGE_DELIMITER = ":"

ROLL_COMMAND = "!roll"
TRACE_COMMAND = "!trace"
HELP_COMMAND = "!help"
COMMANDS = [ROLL_COMMAND, TRACE_COMMAND, HELP_COMMAND]

INIT_HEADER = "INI"
ROLL_HEADER = "ROL"
CHAT_HEADER = "CHT"
RESULT_HEADER = "RES"
TRACE_HEADER = "TRC"
VAR_HEADER = "VAR"
HEADERS = [INIT_HEADER, ROLL_HEADER, CHAT_HEADER, RESULT_HEADER, 
TRACE_HEADER, VAR_HEADER]

# >>> list(filter(None, a.split(":")))